name: Variablen-Demo

env:
  ENV: production
  VERSION: v1.0

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    name: Global Variablen verwenden
    runs-on: ubuntu-latest
    steps:
      - name: ENV und VERSION ausgeben
        run: |
          echo "Globale ENV: $ENV"
          echo "Globale VERSION: $VERSION"

  job2:
    name: Variable überschreiben
    runs-on: ubuntu-latest
    env:
      VERSION: v2.0
    steps:
      - name: Überschriebene VERSION ausgeben
        run: |
          echo "ENV bleibt: $ENV"
          echo "Überschriebene VERSION: $VERSION"

  secret_job:
    name: Secret verwenden
    runs-on: ubuntu-latest
    steps:
      - name: Dummy-Ausgabe ohne Secret sichtbar zu machen
        run: |
          echo "Das Secret ist sicher gespeichert"
          echo "Die Länge des Secrets ist: ${#MY_SECRET}"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

  output_job:
    name: Output erzeugen und verwenden
    runs-on: ubuntu-latest

    outputs:
      custom_output: ${{ steps.generate_output.outputs.result }}

    steps:
      - name: Output erzeugen
        id: generate_output
        run: echo "result=Erfolgreich erzeugt" >> $GITHUB_OUTPUT

      - name: Output verwenden
        run: echo "Output war ${{ steps.generate_output.outputs.result }}"
  matrix_job:
    name: Node.js-Versionen testen
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Node Version installieren
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Node Version anzeigen
        run: node -v
        