name: Variablen-Demo

env:
  ENV: production
  VERSION: v1.0

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    name: Global Variablen verwenden
    runs-on: ubuntu-latest
    steps:
      - name: ENV und VERSION ausgeben
        run: |
          echo "Globale ENV: $ENV"
          echo "Globale VERSION: $VERSION"

  job2:
    name: Variable überschreiben
    runs-on: ubuntu-latest
    env:
      VERSION: v2.0
    steps:
      - name: Überschriebene VERSION ausgeben
        run: |
          echo "ENV bleibt: $ENV"
          echo "Überschriebene VERSION: $VERSION"

  secret_job:
    name: Secret verwenden
    runs-on: ubuntu-latest
    steps:
      - name: Dummy-Ausgabe ohne Secret sichtbar zu machen
        run: |
          echo "Das Secret ist sicher gespeichert"
          echo "Die Länge des Secrets ist: ${#MY_SECRET}"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
